### PR TITLE
Added footer 

### LINKED ISSUE #10: Add a footer.

### PR DESCRIPTION
**Pull request by promaroy**
added footer for issue #10

### CODE REVIEW

**Review by ADRE9 — CHANGES_REQUESTED** [review]
Can yo do the PR to the branch-1? Merging PR to the master is not what we should do. Rest things look good for now. So can you attach a screenshot of the app with your footer?

**Comment by ADRE9** [comment]
@promaroy moreover the footer is floating. Make it static and at the bottom of the page.

**Comment by promaroy** [comment]
Sure, I am making the necessary changes

**Comment by promaroy** [comment]
I have made the changes and made a separate pull request to  branch 1 along with the screenshot.

**Pull request closed without merging**
