### PR TITLE
Prettier added

### PR DESCRIPTION
**Pull request by rishabhborn2win**
Formatted the code make it readable easily.

# Description:

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### Fixes #(issue_no):

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [X] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by ADRE9 — CHANGES_REQUESTED** [review]
Resolve the conflicts.

**Comment by ADRE9** [comment]
Make the PR to the prettier branch instead of master . If things don't break we'll merge it.

**Review by ADRE9 — APPROVED** [review]

**Comment by rishabhborn2win** [comment]
I have updated the base branch please merge and check for the breaks and let me know if there is any kind of issue present in the PR.

**Comment by ADRE9** [comment]
Sure we will go through it.

**Pull request merged**
