### PR TITLE
Adding the sender email and a suitable subject, issue #49

### LINKED ISSUE #49: Add the sender email and add a suitable subject
Adding the sender mail in nodemailer function to adrenine13@gmail.com and adding relevant subject.

### PR DESCRIPTION
**Pull request by udaymittal7**
Added the sender email to 'adrenine13@gmail.com' and added subject as 'Welcome to Bunk Manager'
issue # 49

### CODE REVIEW

**Comment by ADRE9** [comment]
Is it working? Can you confirm with the screenshot of the email?

**Comment by udaymittal7** [comment]
@ADRE9 Actually you have to add the password of your email in .env file for the gmail service to work.

**Comment by ADRE9** [comment]
> @ADRE9 Actually you have to add the password of your email in .env file for the gmail service to work.

I understand. Use your email for a while.

**Comment by udaymittal7** [comment]
Can you send me the sample dev.env file so I will be able to run the server?

**Comment by udaymittal7** [comment]
I tried it on one of my projects it is working. It will work just fine in this as well I hope.

**Review by ADRE9 — APPROVED** [review]

**Pull request merged**
