### PR TITLE
Added the nodemailer functionality for when a new user signup

### LINKED ISSUE #14: Send email when user sign up using node-mailer

### PR DESCRIPTION
**Pull request by udaymittal7**
Added a new email.js file in utils for the nodemailer email functionality for when a new user signup and updated the user controller file.

We have to add EMAIL_USERNAME and EMAIL_PASSWORD in the .env file for the nodemailer function to accept and send the email.

I have created the email.js file such that we can use this for sending emails for different purposes too.

Please verify and let me know what can I do improvise the code or if there is any error.

### CODE REVIEW

**Comment by ADRE9** [comment]
Can @Mustafiz04  review it asap.

**Comment by Mustafiz04** [comment]
Yes I'm reviewing.

**Comment by Mustafiz04** [comment]
Instead of creating class please create a function that take name, email, department, roles and regdId.
Also write proper welcome message using all these parameter mention above.

Is it run in proper way on your local computer??
All other code is correct. 
Waiting for your updated code.

**Comment by udaymittal7** [comment]
Okay, I will create the function for it instead of a class with the required parameters.
Yes, it worked just fine.
Should I make another PR and remove this one or just update?

**Comment by Mustafiz04** [comment]
No need to delete.
Just merge/squash all your PR in one then make a new PR.

**Comment by udaymittal7** [comment]
I just updated the changes and made the commit.

**Comment by udaymittal7** [comment]
@Mustafiz04 @ADRE9 Please add the relevant tags of GSSOC'21 as I see other PRs have that and not mine.
Thank you.

**Comment by udaymittal7** [comment]
@ADRE9 Please also mark issue #14 in the issues panel closed. Thank you.

**Comment by ADRE9** [comment]
Create a new issue to add the sender email as adrenine13@gmail.com and add a suitable subject. I'll assign it to you. @udaymittal7

**Comment by udaymittal7** [comment]
@ADRE9 Okay. I am gonna create the issue right away.

**Comment by udaymittal7** [comment]
@ADRE9 Hey, just one request. In the original issue, you marked this issue as level 3 but in this you marked this as level 2. Please mark this as level 3 too. Thank you.

**Pull request merged**
