### PR TITLE
Issue 30 Added Favicon 

### LINKED ISSUE #30: Change default favicon
Hey!
I noticed that we still have the default **favicon** that comes with React boilerplate code. I would to like to change it to the one that fits our theme as a GSSOC`21 participant. 
@ADRE9

### PR DESCRIPTION
**Pull request by dig9074vijay**
Fixed #30 
Added favicon and splash screen logo for android and iOS progressive web apps.
Screenshot 2021-03-11 at 5 21 50 PM

### CODE REVIEW

**Review by ADRE9 — APPROVED** [review]
cool!

**Comment by ADRE9** [comment]
Can you add the package-lock.json file. We'll update it. @dig9074vijay

**Comment by dig9074vijay** [comment]
Yeah sure! @ADRE9

**Comment by dig9074vijay** [comment]
@ADRE9 I have added the package-lock.json file.

**Pull request merged**
