### PR TITLE
Added Google OAuth logo 

### LINKED ISSUE #22: The logo for the Instagram needs to be replaced with that of Google
The OAuth logo for Instagram needs to be replaced with that of the Google. Participants contact @Sanyam2000-dot for guidance.

### PR DESCRIPTION
**Pull request by Muditxofficial**
Replaced instagram Oauth logo with that of google.
For Issue #22

### CODE REVIEW

**Review by ADRE9 — CHANGES_REQUESTED** [review]
Use the material-ui icon instead of a svg icon. 
https://material-ui.com/components/material-icons/#material-icons

**Comment by Muditxofficial** [comment]
@ADRE9 there is no google icon in material ui that's why i used svg.

**Comment by ADRE9** [comment]
Okay then @Muditxofficial can you attach a screenshot.

**Comment by Muditxofficial** [comment]
gsvg
Hope this looks good.

**Comment by ADRE9** [comment]
> gsvg
> Hope this looks good.

Comment out the code for Facebook for now. And yes, it looks awesome.

**Pull request merged**
