### PR TITLE
Made footer mobile responsive and increased icon sizes

### LINKED ISSUE #100: Make the Footer Mobile responsive
**Deliverables:**

- [ ] Make the footer mobile responsive.
- [ ] Make the icon size a little bigger.

**Screenshots**
Screenshot (233)

### PR DESCRIPTION
**Pull request by FireQueen-3010**
# Description:

1) Increased the social icon size in mobile view.
2) Made the whole footer mobile responsive by making changes in elements that needed to be fixed.
### Fixes #(100): 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [x] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Screenshots:
**Before:** 
image
**After:**
image

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @ADRE9 @Sanyam2000-dot :)

**Comment by Sanyam2000-dot** [comment]
Please add some padding between the icons.

**Comment by FireQueen-3010** [comment]
Okay

**Comment by FireQueen-3010** [comment]
Made the required changes pls review :) @Sanyam2000-dot

**Comment by ADRE9** [comment]
And also the GitHub icon looks larger as compared to other. Make it white instead of whatever color it has right now.

**Comment by FireQueen-3010** [comment]
image

**Comment by FireQueen-3010** [comment]
> And also the GitHub icon looks larger as compared to other. Make it white instead of whatever color it has right now.

All the icons white or only the github one? @ADRE9 also if I change it to white, do I need to change the hover color as well? 'cause right now hover color is white

**Comment by ADRE9** [comment]
Let there be no hover color. Just scale it by 1.01 that'll be fine. And about white yes , make every icon white.

**Comment by FireQueen-3010** [comment]
Okay

**Comment by FireQueen-3010** [comment]
image
Made the req changes please review @ADRE9

**Comment by ADRE9** [comment]
Just add the screenshot for the desktop once and we can confirm the merge.

**Comment by FireQueen-3010** [comment]
image
I didn't change anything in the desktop view :) @ADRE9

**Comment by ADRE9** [comment]
Just the color to white 👍🏻.

**Comment by FireQueen-3010** [comment]
Done  @ADRE9 
image

**Review by ADRE9 — APPROVED** [review]

**Pull request merged**
