### PR TITLE
Updated Readme.md Mern Stack

### LINKED ISSUE #71: Update the Tech Stack of the project in Readme
**Deliverables:**
Add the deliverables with their description here.
- [x] Update tech stack to MERN in readme.md file.

**Screenshots**
Add any relevant screenshots to show how the elements look or works currently/how the enhanced element should look or function.

### PR DESCRIPTION
**Pull request by Muditxofficial**
# Description:

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### Fixes #71 :

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [x] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Screenshots:
image

### CODE REVIEW

**Comment by ADRE9** [comment]
Can you also add the other libraries used. Refer the package.json files to check out all the major libraries and have a talk to @Sanyam2000-dot if any doubt persists.

**Comment by Muditxofficial** [comment]
Should i add in one row only or like "Other Libraries Used:" then badges. Also, no respond from mentioned person.

**Comment by Sanyam2000-dot** [comment]
Libraries used then their badges. Please ask the doubt how would you expect me to know that you are facing any.

**Comment by Sanyam2000-dot** [comment]
> Should i add in one row only or like "Other Libraries Used:" then badges. Also, no respond from mentioned person.

The latter one libraries used then badges. And please ask the doubt first else how would you expect me to know that you are facing any.

**Comment by Muditxofficial** [comment]
image
This is good enough, i think.

**Comment by Sanyam2000-dot** [comment]
> image
> This is good enough, i think.

Well Done!

**Review by ADRE9 — APPROVED** [review]
Cool!

**Comment by ADRE9** [comment]
@Muditxofficial you have not added the libraries section. Add it.

**Comment by Muditxofficial** [comment]
@ADRE9 Ok i will send a new pr and you can just merge it .

**Comment by Muditxofficial** [comment]
I created a pr. Now you can merge it. Apologies for this :)

**Pull request merged**
