### PR TITLE
Web app logo

### PR DESCRIPTION
**Pull request by vtejaeta**
# Description:

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### Fixes #(94):

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [x] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Screenshots:
image

### CODE REVIEW

**Comment by vtejaeta** [comment]
I have added new app logo as favicon in the code

**Comment by ADRE9** [comment]
Any screenshot??

**Comment by vtejaeta** [comment]
https://user-images.githubusercontent.com/65386350/114269316-0d71e400-9a24-11eb-9eca-74a5a3a7a422.png

Can you please refer above link for screenshot.

Thanks

**Comment by Mustafiz04** [comment]
look good.

**Comment by vtejaeta** [comment]
64x64_bunk_manager

This is 64x64 logo which was used as favicon in the code.

For SVG -
https://svgshare.com/i/W0M.svg

**Comment by vtejaeta** [comment]
Hey @Sanyam2000-dot  Can you please add label GSSOC for this pull request

**Comment by vtejaeta** [comment]
Thanks

**Pull request merged**
