### PR TITLE
added mongoose event listeners

### LINKED ISSUE #76: Add mongoose event listeners
Required is to add event listeners at DB connection file

   ```
 mongoose.connection.on('connected', () => {
        console.log('DB Connection Established')
    })
```

This is example of event listener when DB is connected.
Also have to add for Disconnected, Re-established, connection closed and throw error while some error occurs.

Have any doubt do ask her freely.
Good Luck.

### PR DESCRIPTION
**Pull request by promaroy**
# Description:

Added mongoose event listeners for events like connected, disconnected , connection stopped by app termination, etc.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [x] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Screenshots:
mongoose_event_listeners

### CODE REVIEW

**Comment by Mustafiz04** [comment]
@promaroy Your code is correct but need some modification
write in sequence 
1. Write whole connection code inside a async await function and name it connectDB
2. Listener in sequence (i) connected (ii) reconnected (iii) disconnected (iv) close (v) then error  in same way you have written for connected
3. then write await mongoose.connect( )
4. export default connectDB
5. import and call the function.

If any doubt ask here or in discord.

**Comment by promaroy** [comment]
@Mustafiz04 I have made the above mentioned changes. Please have a look!

**Comment by Mustafiz04** [comment]
@promaroy all code look good.
It running perfect in your localhost?

If yes then I will merge it.

**Comment by promaroy** [comment]
@Mustafiz04 yes it's running perfectly on localhost with zero warnings

**Comment by Mustafiz04** [comment]
Great

**Comment by promaroy** [comment]
@Mustafiz04   please add GSSOC21 tag and a difficulty level tag to the PR.

**Comment by Mustafiz04** [comment]
Yes I am trying to add but it does not
@ADRE9 please look into it.

**Pull request merged**
