### PR TITLE
Fixed Issue: 69 | Get In Touch Section Has added to the Footer!!!

### PR DESCRIPTION
**Pull request by ASHISH-GITHUB2495**
# Description:
>Get in touch section (forms) in footer have been added.
>icons of social media has ben added
>All the element are from **material ui**
### Fixes #(69):

# By Project admin(Sir)
1.update the social media link ,currently mine added.
2.update the code for handleSend() , all values of forms will be there.
3.I have used simple html validation of form, because i dont know much about it.

_**Sir, i also want to contribute to Header section ... if you let me , just give me logo/icon of website sir **_

## Screenshots:
Screenshot (18)

### CODE REVIEW

**Comment by ADRE9** [comment]
@ASHISH-GITHUB2495 can you send me the screenshots for mobile version and @kunaljain0212 and @Sanyam2000-dot can you both review the codes. And for header we will provide you with logo after 27th. Designers are all busy.

**Review by ADRE9 — CHANGES_REQUESTED** [review]
You have used the withStyles hoc instead use the the already used makeStyles hook. And you can use the Formik library for handling forms.

**Review by ADRE9 — APPROVED** [review]
For now I am approving but create another issue that implements the above required changes. Good job buddy!

**Comment by ASHISH-GITHUB2495** [comment]
> You have used the withStyles hoc instead use the the already used makeStyles hook. And you can use the Formik library for handling forms.

Sir, it's only 1-2 moths i have learned about MERN technology... Formik library, material Ui , withStyke... are much harder for me for now... and I am preparing for my wipro internship exam on 3rd April.. after this i will give my full time to this open source.

**Comment by Mustafiz04** [comment]
This event is also about to get familiar with different tools and technology.
We are here to help and teach you.
Ask any doubt in discord group

@ASHISH-GITHUB2495 No problem.
Prepare for the exam.
Best of Luck
We are waiting for you and expecting from to contribute as much as possible.

**Comment by ASHISH-GITHUB2495** [comment]
> This event is also about to get familiar with different tools and technology.
> We are here to help and teach you.
> Ask any doubt in discord group
> 
> @ASHISH-GITHUB2495 No problem.
> Prepare for the exam.
> Best of Luck
> We are waiting for you and expecting from to contribute as much as possible.

Thank you sir.. trying to get back as soon as possible.

**Review by ADRE9 — COMMENTED** [review]
Resolve All Conflicts

**Comment by ASHISH-GITHUB2495** [comment]
Sir, can you please merge this pull request... i have not any sucessfull merge of my pull request. Later i will create one more issue for  you above task...for adding more feature...

**Review by ADRE9 — COMMENTED** [review]
Create another issue so that it gets refactored soon.

**Pull request merged**
