### PR TITLE
validators

### LINKED ISSUE #77: Add validator to every required field in the form like Email, username, password etc using express-validator
Write validator function as middleware. It should be before the actual controller function in every routes that take input from client side.

For example - 

Email - should be email with proper formate
Username - should be unique and at-least 6 character long
Password - should be 8 character long which include at-least 1 special character, 1 capital letter
Semester - should not be greater than 8

and so on.

Have any doubt feel free to ask her.
Good Luck

### PR DESCRIPTION
**Pull request by Muditxofficial**
# Description:
Added validator to required field in the form like Email, username, password etc using express-validator package
in login,signup

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [x] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by ADRE9** [comment]
Write proper heading and description. It's not the way to make a pull request.

**Comment by Mustafiz04** [comment]
@Muditxofficial there are more API which take input from frontend apart from signin and signup.
Please find all those APIs and apply that validator to it.

**Comment by Muditxofficial** [comment]
> @Muditxofficial there are more API which take input from frontend apart from signin and signup.
> Please find all those APIs and apply that validator to it.

yes, sure. I have added createSubject validator(not pushed yet).
So, should i also add in update routes as its upto user which field he chooses.
Also,createTemplate and createAttendence has not been implemented and i am not sure how to work around them. Thanks.

**Comment by Mustafiz04** [comment]
Yes you should.
Make PR i will look into it.
This is your task to find out all the route and add validator to it.
If added then make PR.

**Comment by Muditxofficial** [comment]
Now see if something needs to corrected or its fine :)

**Comment by Mustafiz04** [comment]
@Muditxofficial have your check APIs is it run in the proper way ???

**Comment by Mustafiz04** [comment]
have you checked all APIs?
Is any more left ??

**Comment by Muditxofficial** [comment]
githi
What could've been wrong here ? yeah, i think covered most except create template one.

**Comment by Mustafiz04** [comment]
Why not you use postman?
And how you make PR without cross-checking in your locals ??

**Comment by Mustafiz04** [comment]
Hello @Muditxofficial you take a lot of time for this issue.
Please do it in 2-3 days.
If you have any doubt ask in the discord group or we can conduct a meet where you can raise your issues.
If not then please complete it soon.

**Pull request closed without merging**
